{% set name = "kikuchipy" %}
{% set version = "0.2.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 8fe9306b4d293e00f4bd56a6a2514b51f2b6ba247525980de742755f67012d34

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps --ignore-installed -vv

requirements:
  host:
    - pip
    - python >=3
  run:
    - python >=3
    - dask
    - hyperspy >=1.5.2
    - h5py
    - matplotlib
    - numpy >=1.17
    - scikit-image >=0.16,<0.17
    - scikit-learn
    - scipy

test:
  requires:
    - pytest >=5.3.2
  imports:
    - kikuchipy
    - kikuchipy.filters
    - kikuchipy.generators
    - kikuchipy.io
    - kikuchipy.pattern
    - kikuchipy.pattern.chunk
    - kikuchipy.signals
    - kikuchipy.release
  commands:
    - pytest --pyargs kikuchipy

about:
  home: https://kikuchipy.org
  license: GPL-3.0-or-later
  license_file: LICENSE
  summary: |
    kikuchipy is an open-source Python library for processing and analysis of
    electron backscatter diffraction (EBSD) patterns
  doc_url: https://kikuchipy.org
  dev_url: https://github.com/kikuchipy/kikuchipy

extra:
  recipe-maintainers:
    - hakonanes
